### ISSUE TITLE
After login, I still can access sign up page.

### ISSUE THREAD

**Issue by ganjarsetia** [gothinkster/apprun-realworld-example-app#2]
Try login and then access the sign up page.

![image](https://user-images.githubusercontent.com/3258090/57095856-091ff500-6d3e-11e9-8683-86a0067a46fa.png)

I believe this is wrong. Same with the sign in page.

**Comment by yysun** [comment]
Fixed in a2897bc.

**Comment by yysun** [comment]
Fixed again in 7534594.
